11:16:44.609  root      : INFO    : ++++++++ Fri Oct 27 11:16:44 2023 ++++++++
11:16:44.697  scapy.runtime: WARNING : No route found for IPv6 destination :: (no default route?)
11:16:44.714  root      : WARNING : VXLAN support not found in Scapy
11:16:44.714  root      : WARNING : ERSPAN support not found in Scapy
11:16:44.714  root      : INFO    : GENEVE support found in Scapy
11:16:44.715  root      : INFO    : MPLS support found in Scapy
11:16:44.715  root      : WARNING : NVGRE support not found in Scapy
11:16:44.716  root      : INFO    : IGMP support found in Scapy
11:16:44.727  root      : DEBUG   : Parsed test parameters:
11:16:44.727  root      : DEBUG   : 	*p4info=/p4c-out/p4info.txt
11:16:44.727  root      : DEBUG   : 	*cpu_port=255
11:16:44.727  root      : DEBUG   : 	*grpcaddr=localhost:28000
11:16:44.727  root      : DEBUG   : 	*device_id=1
11:16:44.727  root      : DEBUG   : If something is missing, make sure you used the correct syntax: --test-params="[k=v;]*k=v"
11:16:44.766  root      : INFO    : Importing platform: eth
11:16:44.766  root      : DEBUG   : Configuration: {'xunit_dir': 'xunit', 'disable_ipv6': False, 'minsize': 0, 'list_test_names': False, 'test_file': None, 'test_spec': '', 'allow_user': False, 'test_order_seed': 2746, 'default_negative_timeout': 0.1, 'platform': 'eth', 'log_dir': None, 'xunit': False, 'disable_erspan': False, 'device_sockets': [], 'disable_geneve': False, 'socket_recv_size': 4096, 'profile': False, 'default_timeout': 2.0, 'platform_args': None, 'relax': False, 'random_seed': None, 'interfaces': [(0, 1, 'veth1'), (0, 2, 'veth3'), (0, 3, 'veth5'), (0, 4, 'veth7'), (0, 5, 'veth9'), (0, 6, 'veth11'), (0, 7, 'veth13'), (0, 8, 'veth15')], 'test_case_timeout': None, 'port_map': {(0, 1): 'veth1', (0, 7): 'veth13', (0, 6): 'veth11', (0, 5): 'veth9', (0, 4): 'veth7', (0, 3): 'veth5', (0, 8): 'veth15', (0, 2): 'veth3'}, 'disable_vxlan': False, 'disable_nvgre': False, 'qlen': 100, 'test_order': 'default', 'profile_file': 'profile.out', 'fail_skipped': False, 'test_params': "p4info='/p4c-out/p4info.txt';grpcaddr='localhost:28000';device_id='1';cpu_port='255'", 'test_dir': './tests', 'list': False, 'platform_dir': '/usr/local/lib/python2.7/dist-packages/ptf/platforms', 'disable_igmp': False, 'disable_mpls': False, 'debug': 'verbose', 'log_file': 'ptf.log', 'failfast': False}
11:16:44.766  root      : INFO    : port map: {(0, 1): 'veth1', (0, 7): 'veth13', (0, 6): 'veth11', (0, 5): 'veth9', (0, 4): 'veth7', (0, 3): 'veth5', (0, 8): 'veth15', (0, 2): 'veth3'}
11:16:44.766  root      : INFO    : Autogen random seed: 43698011
11:16:44.768  root      : INFO    : *** TEST RUN START: Fri Oct 27 11:16:44 2023
11:16:44.769  root      : INFO    : ** START TEST CASE vla.VlaRoute
11:16:44.817  dataplane : DEBUG   : Sending 111 bytes to device 0, port 1
11:16:44.818  root      : DEBUG   : Checking for pkt on device 0, port 2
11:16:44.818  dataplane : DEBUG   : Grabbing packet
11:16:44.818  dataplane : DEBUG   : Out of packets on device 0, port 2
11:16:44.818  dataplane : DEBUG   : Did not find packet
11:16:45.784  dataplane : DEBUG   : Grabbing packet
11:16:45.784  dataplane : DEBUG   : Out of packets on device 0, port 2
11:16:45.784  dataplane : DEBUG   : Did not find packet
11:16:46.800  dataplane : DEBUG   : Grabbing packet
11:16:46.801  dataplane : DEBUG   : Out of packets on device 0, port 2
11:16:46.801  dataplane : DEBUG   : Did not find packet
11:16:46.818  dataplane : DEBUG   : Poll timeout, no packet from device 0, port 2
11:16:46.837  root      : INFO    : ** END TEST CASE vla.VlaRoute
11:16:46.838  root      : INFO    : *** TEST RUN END  : Fri Oct 27 11:16:46 2023
11:16:46.838  root      : INFO    : *** TEST RUN END  : Fri Oct 27 11:16:46 2023
11:16:46.838  dataplane : INFO    : Thread exit
11:16:46.838  dataplane : INFO    : Thread exit
